include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_slow_async_io
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_relative_imports
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
