name: flip_board_example
description: FlipWidget examples
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  async: ^2.6.1
  flip_board:
    path: ../
    
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - assets/bird.png
    - assets/butterfly.png
    - assets/flower.png
    - assets/flutter.png
    - assets/sea.png
