name: flip_board
description: A package for flip widgets
version: 0.4.0
homepage: https://github.com/cc-nogueira/flip_board

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.6.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
